### ISSUE TITLE
Delete or add Settings resolves in null response from API

### ISSUE THREAD

**Issue by etheliene** [codersantosh/wp-react-plugin-boilerplate#8]
Describe the bug:

When alternating the default options, the API returns a NULL response.

Following scenario:

1. Modify `/src/admin/pages/advanced` -> remove 'setting_5' section
2. Modify `/admin/class-wp-react-boilerplate-admin.php` -> remove setting_5 in schema
3. Modify `/includes/functions.php` -> remove 'setting_5' from `$default_theme_optoins`

Run: {yarn|npm} start / build

The response from the API is the following:

` wp_react_plugin_boilerplate_options: null`

Expected Behaviour: 
Return the remaining or modified options

**Comment by codersantosh** [comment]
When the setting's value is saved and later schema is changed in  [register_settings](https://github.com/codersantosh/wp-react-plugin-boilerplate/blob/master/admin/class-wp-react-plugin-boilerplate-admin.php#L164), WP_REST_Settings_Controller [rest_validate_value_from_schema](https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-settings-controller.php#L131) return null. 

It seems that the saved options keys from the database should be in the registered schema to return the value from the WordPress settings rest API. Could you put the following code on your plugin, the issue should be fixed.

```
function prefix_wp_react_plugin_boilerplate_fix_schema($option_group, $option_name, $args ){

    if( $option_name === 'wp_react_plugin_boilerplate_options'){
        $my_options = get_option( $option_name, $args['default'] );
        $my_options_keys = array_keys($my_options);

        $schema_properties = $args['show_in_rest']['schema']['properties'];
        $schema_properties_keys = array_keys($schema_properties);

        $different_keys = array_diff($my_options_keys,$schema_properties_keys);
        if( $different_keys ){
            foreach ( $different_keys as $key){
                unset($my_options[$key]);
            }
            update_option( $option_name, $my_options);
        }
    }
}
add_action('register_setting','prefix_wp_react_plugin_boilerplate_fix_schema',10,3);
```

Note: Do not forget to change `wp_react_plugin_boilerplate_options` to your plugin options name.

**Comment by codersantosh** [comment]
It does not exist on version 2, with using custom API.
